### PR TITLE
Update echo-ISR.ino - waste a byte

### PR DESCRIPTION
**Pull request by Kaspi314**
dirty hack - remove erroneous byte present in echo data from ISR.

not sure why this works.

### CODE REVIEW

**Comment by Kaspi314** [comment]
I should probably try to actually setup git on the local machine instead of carefully pasting into the web editor and committing directly to master..

I'm planning on writing a library to address this multiplexer but I'm having problems doing that without making too many changes to picoUART. I might use some helper functions to support it as a separate library but definitely need to be able to define which pin is RX and TX. (automatic channel switching is more difficult)

**Comment by Kaspi314** [comment]
https://github.com/nerdralph/picoUART/pull/6/commits/4990e6c27d72c3d20e88cea20ddaab5b3fb8b0e2

this one works I'm not sure about the rest of these or #define outside of a header and the compilers ordering.

**Comment by nerdralph** [comment]
I'm not convinced you've found a bug in echo-ISR.
The pu_config.h change looks OK.  I'll likely merge that.
The mux example is more about showing how to control the mux than it is about picoUART, so I'll leave that out of the merge.

**Comment by Kaspi314** [comment]
> I'm not convinced you've found a bug in echo-ISR.

I can take screenshots and show what I'm doing but I keep getting an extra byte at the beginning of the message returned after "got: " there is a null byte being thrown in there and then the byte(s) sent.

using: picocore and attiny85 with a cheap CH340 dongle. Arduino IDE 1.8.12

I don't have a scope to look at what it is actually doing but is on my list of things even a cheap DSO would be nice in this case.

I will provide a screenshot give me some time. I was just looking at jumper wire on amazon and soldering some things and saw this in my email.

I'm actually working on

> The pu_config.h change looks OK. I'll likely merge that.

I hope so. It looks entirely reasonable I wish I could get it to actually work in arduino IDE and with the avr-gcc.  (by that merit I also cannot get the baudrate #define to work in my sketches either. I'm not sure why.)

> The mux example is more about showing how to control the mux than it is about picoUART, so I'll leave that out of the merge.

that is understandable and not necessary for a merge but I thought it was cool to have available for anyone on github as you can use the ISR with a mux and it seems to work.

I'm not sure if you would normally disable interrupts for something like this, or if reading analog values could trigger ISR while the pin is on INPUT.

I'm actually working on a solar tracker here: https://github.com/Kaspi314/SolarTrackerAttiny85

which is planned to use RS485 half duplex to connect to an ESP32 for managing an array of solar panels (hence the using picoUART with attiny85 to read sensors and control motors.)

As related to my inability to solve gcc compiling with #define in reply to your second line of comment, if you look there you will see what I am having to do but this is probably my compiler issue or lack of making a header file or something. I dont really know and google hasn't been very helpful and trying to use #undef and then #define in my sketch doesn't seem to work.

(maybe this is because gcc only does that when it is a library and not in the project? but I think I tried that to begin with.)

**Comment by nerdralph** [comment]
I just re-tested the ISR echo test with a t85@16M and the default settings, and it's working fine.  Were you trying to use it in one-wire mode?  That's not supported in the interrupt-driven mode:
"Currently 1-wire shared Rx/Tx is not supported with PCINT-based receive."

**Comment by Kaspi314** [comment]
> I just re-tested the ISR echo test with a t85@16M and the default settings, and it's working fine. Were you trying to use it in one-wire mode? That's not supported in the interrupt-driven mode:

mine is at 8mhz I will try 16 but at 8mhz it is doing that.

Before I send this let me double check.

> "Currently 1-wire shared Rx/Tx is not supported with PCINT-based receive."
I was. I had also tried on pins 3,4 not the usual 0,1 and it was working fine on 0,1 not 3,4

I just follwed these steps and it seems to work fine OOTB:

using USBasp

On a new attiny85 I used avrdude and flashed micronucleus 8mhz.

then I flashed the "bootloader" in arduino IDE for attiny85 from here: https://raw.githubusercontent.com/damellis/attiny/ide-1.6.x-boards-manager/package_damellis_attiny_index.json

When doing so i assured it was on 8mhz to set fuses.

Then I flashed the "bootloader" for picocore from arduino IDE.  It complained about using 0x3f on fuses but whatever.

then I flashed the clock util and calibrated the clock

and then I flashed picoUart ISR example at 9600 baud and it worked.

I'm not sure why it doesn't work right on my other chips but this was on a brand new chip so you're right I might just have a weird chip.

**Comment by Kaspi314** [comment]
PS it does work with that hack in one wire mode I'm not sure why but it throws in an extra byte  and that does work correctly with a multiplexer but I don't know how much the ISR is discarding data in the background while running delay() on other things between serial connections.

(or how discarding spurious transmissions works.)

**Comment by nerdralph** [comment]
> then I flashed the clock util and calibrated the clock

Most t85's are fine without OSCCAL tuning.  It's mainly on t13's I've found the default OSCCAL is not close enough to 4.8M/9.6M for reliable high-speed serial.

If you don't like using your USBasp and prefer a bootloader, I'd suggest trying one I've written:
https://github.com/nerdralph/picoboot-lib
It's much smaller than micronucleus, and includes automatic OSCCAL tuning.

**Comment by nerdralph** [comment]
> 
> 
> PS it does work with that hack in one wire mode I'm not sure why but it throws in an extra byte and that does work correctly with a multiplexer but I don't know how much the ISR is discarding data in the background while running delay() on other things between serial connections.
> 
> (or how discarding spurious transmissions works.)

Supporting one-wire mode is something I may still add to the ISR version.  It shouldn't take much more than disabling the Rx ISR during Tx.

**Comment by Kaspi314** [comment]
> > PS it does work with that hack in one wire mode I'm not sure why but it throws in an extra byte and that does work correctly with a multiplexer but I don't know how much the ISR is discarding data in the background while running delay() on other things between serial connections.
> > (or how discarding spurious transmissions works.)
> 
> Supporting one-wire mode is something I may still add to the ISR version. It shouldn't take much more than disabling the Rx ISR during Tx.

awesome. 


thanks for the great projects and everything.

I wish I could figure out how to disable and enable individual ISRs. That could be a project to it's self.

**Pull request closed without merging**
